### ISSUE TITLE
Try packing more data into each AppendRequestMessage for better performance

### ISSUE THREAD

**Issue by arssher** [zenithdb/zenith#1005]
The first idea is to not read next piece of WAL untill previous one was streamed to majority.

**Comment by petuhovskiy** [comment]
Tried to do it in https://github.com/zenithdb/postgres/pull/120, but it didn't help, amount of WAL in WalMessage and performance stayed the same. My guess is that we're having a problem somewhere else, because latest tests showed low performance is reproduced even with single safekeeper and relatively high amount of WAL in WalMessage.

**Comment by petuhovskiy** [comment]
> Hm, is it true, i.e. single safekeeper yields bigger WalMessages but performance doesn't change? I thought/expected we have the same 150 vs 800 bytes picture there.

Nope, WAL message sizes are completely different in local tests, I wrote more details in https://github.com/zenithdb/zenith/issues/1141.

**Comment by stepashka** [comment]
this may become irrelevant once #1337 is complete
sending to backlog

**Comment by stepashka** [comment]
marking as closed becase this will be irrelevant with #1337
