### ISSUE TITLE
Handling out-of-disk space by Zenith

### ISSUE THREAD

**Issue by knizhnik** [zenithdb/zenith#1065]
I wonder what is the desired behavior of pageserver on out-of-disk space error?
Right now it depends on in which context it happen. Some times page server reports error, but doesn't terminate thread.
Sometime it panics:
```
thread 'main' panicked at 'ChapterWriter was dropped without calling close()', /home/knizhnik/.cargo/git/checkouts/bookfile-be7470723ab9e1d7/d51a99c/src/book.rs:252:17
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/std/src/panicking.rs:525:12
   1: <bookfile::book::ChapterWriter<W> as core::ops::drop::Drop>::drop
             at /home/knizhnik/.cargo/git/checkouts/bookfile-be7470723ab9e1d7/d51a99c/src/book.rs:252:17
   2: core::ptr::drop_in_place<bookfile::book::ChapterWriter<std::io::buffered::bufwriter::BufWriter<pageserver::virtual_file::VirtualFile>>>
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/ptr/mod.rs:188:1
   3: bookfile::book::ChapterWriter<W>::close
             at /home/knizhnik/.cargo/git/checkouts/bookfile-be7470723ab9e1d7/d51a99c/src/book.rs:240:5
   4: pageserver::layered_repository::delta_layer::DeltaLayerWriter::finish
             at /home/knizhnik/zenith.main/pageserver/src/layered_repository/delta_layer.rs:647:20
   5: pageserver::layered_repository::inmemory_layer::InMemoryLayer::write_to_disk
             at /home/knizhnik/zenith.main/pageserver/src/layered_repository/inmemory_layer.rs:666:31
   6: pageserver::layered_repository::LayeredTimeline::evict_layer
             at /home/knizhnik/zenith.main/pageserver/src/layered_repository.rs:1598:33
   7: pageserver::layered_repository::LayeredTimeline::checkpoint_internal
             at /home/knizhnik/zenith.main/pageserver/src/layered_repository.rs:1493:42
   8: <pageserver::layered_repository::LayeredTimeline as pageserver::repository::Timeline>::checkpoint::{{closure}}
             at /home/knizhnik/zenith.main/pageserver/src/layered_repository.rs:984:46
```

**Comment by SomeoneToIgnore** [comment]
Seems related to https://github.com/zenithdb/zenith/issues/463
I've worked on that in https://github.com/zenithdb/zenith/pull/1394.

In pageserver, we now span the following threads:
https://github.com/zenithdb/zenith/blob/b39d1b17177eb6fe9509b87cb8908f8128ab78bc/pageserver/src/thread_mgr.rs#L73-L106

Before the PR we allowed the `Err`-finished threads to silently exit and logged the panic for panicked threads and allowed them to exit, both did not stop the rest of the pageserver, but poisoned locks usually finished most of the other threads unpredictably later.

After the PR above we
* have reduced the amount of code that can panic in those threads
* always error log if any of the threads panic/returns `Err`
* shut down the entire pageserver on any thread's panic, or `Err` returned from either `GarbageCollector` or `Checkpointer` threads
* do nothing for the rest of the threads:
    * `StorageSync` and `Walreceiver` threads do not return a `Result` in their loop code, so they can only panic or finish successfully
    * `PageRequestHandler` is a short lived thread to handle a connection
    * "connection" threads `LibpqEndpointListener`, `HttpEndpointListener` for now exit and allow the pageserver to continue working: IMO, they should be restarted on errors instead, since `Err` could be caused by clients (abrupt disconnects, timeouts, etc.)


---- 
Out of disk space error seem to be returned mainly as `Err` in the code that managed to reproduce both with manual testing on a limited partition and with a code stub, yet did not consider libraries indeed.
Yet since the pageserver now exits on thread panics, that should be also fine?

@knizhnik do you have any better ideas on how the threads should behave?

**Comment by SomeoneToIgnore** [comment]
Guess not, but feel free to reopen when you get any.
