### ISSUE TITLE
test_branch_behind bug

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#1068]
@arssher :
I'm looking at a curious test_branch_behind CI failure:
https://app.circleci.com/pipelines/github/zenithdb/zenith/3841/workflows/4de5b725-2c42-4183-b707-f7081a018770/jobs/33762/steps

- At 17:03:03.803 final big batch (totally about 64MB of WAL is generated in this test) was inserted;
- At 17:03:19.083 walsender on pg decided to drop the connection with 'terminating walsender process due to replication timeout' -- it means no keepalives were arriving during last 1 minute -- which hints keepalives are broken.
- At 17:03:24.364 walreceiver on pageserver initiated reconnection which hanged for a minute and failed with 'connection closed' at 17:04:24.370. I'm not 100% sure, but I believe these are (the only) lines from failed walsender on pg side:
2021-12-27 17:04:24.368 GMT [1651] LOG:  [ZENITH_SMGR] libpqpagestore: connected to 'postgresql://no_user:@localhost:15300'
2021-12-27 17:04:24.368 GMT [1651] FATAL:  canceling authentication due to timeout

So it looks like walsender went back to pageserver starting pagestream and hanged there.
- Half a second earlier, normal select from test errored out with traditional  Timed out while waiting for WAL record at LSN 0/3EAAD08 due to missing streaming connection, that was the direct test failure reason.

I know there is a hack for walsender: it always requests 0 LSN, otherwise we  deadlock ourselves waiting for WAL for walsender auth which will never arrive as walsender doesn't operate. Thus walsender's page requests must never wait for WAL. However, I'm currently out of ideas was could force 1 minute waiting during walsender auth, when only pagestream request was issued... any thoughts?

**Comment by lubennikovaav** [comment]
I think the problem is that KeepAlive responses from walreceiver are blocked during CG,
because GC holds lock on timelines and this code is waiting for it too
let timeline_synced_disk_consistent_lsn =     tenant_mgr::get_repository_for_tenant(tenantid)?                 .get_timeline_state(timelineid)


On my laptop GC takes 9s and wal_sender_timeout is set to 5s, so it shuts down walsenders before GC completes. 
Though, I still don't get, why  walreceiver fails to reconnect later

**Comment by ololobus** [comment]
Got a random failure of [batch_pg_regress.test_isolation](https://app.circleci.com/pipelines/github/zenithdb/zenith/3832/workflows/50725352-9b85-4812-8d96-be3119a82cff/jobs/33668) recently:
```
test_runner/batch_pg_regress/test_isolation.py:51: in test_isolation
    pg_bin.run(pg_isolation_regress_command, env=env_vars, cwd=runpath)
test_runner/fixtures/zenith_fixtures.py:768: in run
    subprocess.run(command, env=env, cwd=cwd, check=True)
../.pyenv/versions/3.7.10/lib/python3.7/subprocess.py:512: in run
    output=stdout, stderr=stderr)
E   subprocess.CalledProcessError: Command '['/tmp/zenith/pg_install/build/src/test/isolation/pg_isolation_regress', '--use-existing', '--bindir=/tmp/zenith/pg_install/bin', '--dlpath=/tmp/zenith/pg_install/build/src/test/isolation', '--inputdir=/home/circleci/project/vendor/postgres/src/test/isolation', '--schedule=/home/circleci/project/vendor/postgres/src/test/isolation/isolation_schedule']' returned non-zero exit status 1.
```

regression.diffs:
```diff
diff -U3 /home/circleci/project/vendor/postgres/src/test/isolation/expected/multiple-row-versions.out /tmp/test_output/test_isolation/regress/results/multiple-row-versions.out
--- /home/circleci/project/vendor/postgres/src/test/isolation/expected/multiple-row-versions.out	2021-12-27 12:17:06.773926225 +0000
+++ /tmp/test_output/test_isolation/regress/results/multiple-row-versions.out	2021-12-27 12:19:58.390594919 +0000
@@ -1,30 +1,5 @@
 Parsed test spec with 4 sessions
 
 starting permutation: rx1 wx2 c2 wx3 ry3 wy4 rz4 c4 c3 wz1 c1
-step rx1: SELECT * FROM t WHERE id = 1000000;
-     id|txt
--------+---
-1000000|   
-(1 row)
-
-step wx2: UPDATE t SET txt = 'b' WHERE id = 1000000;
-step c2: COMMIT;
-step wx3: UPDATE t SET txt = 'c' WHERE id = 1000000;
-step ry3: SELECT * FROM t WHERE id = 500000;
-    id|txt
-------+---
-500000|   
-(1 row)
-
-step wy4: UPDATE t SET txt = 'd' WHERE id = 500000;
-step rz4: SELECT * FROM t WHERE id = 1;
-id|txt
---+---
- 1|   
-(1 row)
-
-step c4: COMMIT;
-step c3: COMMIT;
-step wz1: UPDATE t SET txt = 'a' WHERE id = 1;
-ERROR:  could not serialize access due to read/write dependencies among transactions
-step c1: COMMIT;
+setup failed: ERROR:  could not read relation existence of rel 1663/16384/20979.1 from page server at lsn 0/04D84970
+DETAIL:  page server returned error: Timed out while waiting for WAL record at LSN 0/4D84970 to arrive, last_record_lsn 0/4AF7D08 disk consistent LSN=0/16962C0
```

Probably related

**Comment by lubennikovaav** [comment]
1. The first part of the problem is failing walreceiver connection.

I think the problem is that KeepAlive responses from walreceiver are blocked during CG,
because GC holds lock on timelines and this code is waiting for it too
let timeline_synced_disk_consistent_lsn = tenant_mgr::get_repository_for_tenant(tenantid)? .get_timeline_state(timelineid)

On my laptop GC takes 9s and wal_sender_timeout is set to 5s, so it shuts down walsenders before GC completes.

2. The second part of the problem is the buffer IO deadlock during walkeeper reconnection.

I've added a log message nearby this comment in bufmgr.c
```
 * If we get here, previous attempts to read the buffer
 * must have failed ... but we shall bravely try again.
 ```
 and observe it in failing test runs.
 
When two backends are trying to load the same buffer, postgres lets one process to do the job, while other hangs waiting for buffer to be available.
See this code: https://github.com/zenithdb/postgres/blob/eb581dbe8c214a6f92c5019f91daf317b5c432e9/src/backend/storage/buffer/bufmgr.c#L1156
 
In postgres it isn't a problem at all, because one process will eventually succeed to read the page, the other will see it and that's it. In zenith, though, different processes may request page at different points in time (see `zenith_get_request_lsn()`)
- select query needs the page at a particular lsn;
- walsender needs the latest version of the page that is available on pageserver.

In our case, select query is trying to read page at lsn 150, while pageserver only has wal up to lsn 100, so it hangs somewhere in `wait_lsn()` and eventually fails with timeout.
The walsender  trying to authenticate to stream wal between lsn 100 and 150, waits for the 1st backend.


I am not quite sure if the first backend is regular client running `select *` from the test or autovacuum process, but I guess it doesn't matter.

**Comment by lubennikovaav** [comment]
I think I could use some help with this.

@hlinnaka , @knizhnik , do you have ideas on how to fix it?

**Comment by arssher** [comment]
Wow, that's funny.

**Comment by knizhnik** [comment]
Situation when compute node is failed to get requested page is more or less normal (non fatal and not assuming some bug in Zenith). Compute node may evict some page, then request it and if page server/safekeeper is crashed/restarted then such page will never be delivered by pageserver. So SMGR failure should not be treated as fatal error. We can abort current transaction, but allow other backends, waiting for this page to retry.

So one possibility is to wrap smgread with TRY/CATCH:

{{{
diff --git a/src/backend/storage/buffer/bufmgr.c b/src/backend/storage/buffer/bufmgr.c
index a90f643270..376d1d723b 100644
--- a/src/backend/storage/buffer/bufmgr.c
+++ b/src/backend/storage/buffer/bufmgr.c
@@ -1012,8 +1012,16 @@ ReadBuffer_common(SMgrRelation smgr, char relpersistence, ForkNumber forkNum,
                        if (track_io_timing)
                                INSTR_TIME_SET_CURRENT(io_start);
 
-                       smgrread(smgr, forkNum, blockNum, (char *) bufBlock);
-
+                       PG_TRY();
+                       {
+                               smgrread(smgr, forkNum, blockNum, (char *) bufBlock);
+                       }
+                       PG_CATCH();
+                       {
+                               TerminateBufferIO(buf, true, 0);
+                               PG_RE_THROW();
+                       }
+                       PG_END_TRY();
                        if (track_io_timing)
                        {
                                INSTR_TIME_SET_CURRENT(io_time);
}}}

Another alternative to to change/extend smgr API by read method returning error instead of throwing exception.

**Comment by hlinnaka** [comment]
> I think I could use some help with this.
> 
> @hlinnaka , @knizhnik , do you have ideas on how to fix it?

Some alternatives:

a) Use safekeepers in all the tests. I believe this is only a problem in the direct postgres<->pageserver connection

b) Reverse the postgres<->pageserver connection so that the compute node connects to pageserver. (https://github.com/zenithdb/zenith/issues/589)

c) Hack the WAL streaming authentication so that when pageserver connects to postgres for WAL streaming, the backend can perform the authentication without accessing the catalogs. Not sure how how much catalog access there is in walsender process startup, how many places we'd need to modify to make that work.

I'd love to get rid of the special case where we use "LSN 0" in the GetPage requests from the walsender process. I believe that's fundamentally unsafe. It happens to usually work, but in principle you might e.g. fetch an old version of an index page into the buffer cache that's missing some entries that you need.

**Comment by arssher** [comment]
+1 on a) actually.

**Comment by knizhnik** [comment]
I do not think that the problem is related only with authorization.
Assume that compute node request some page but pageserver/safekeeper is crashed. Does it mean that compute node also has to be restarted?  Or it can continue work trying to re-establish connection with pageserver/safekeeper ?
In the last case there can be blocked get_page_at_lsn request, which prevents any other attempt to access this page until timeout is expired.

**Comment by lubennikovaav** [comment]
> +1 on a) actually.

+1 on using safekeepers in all the tests

If I understand the problem correctly, it is only auth problem and safekeepers bypass it.
@arssher , I wonder if safekeepers connection may cause any other reads before connection is established?
