### ISSUE TITLE
Take page images in pageserver

### ISSUE THREAD

**Issue by bojanserafimov** [zenithdb/zenith#1142]
AFAIK we currently [don't](https://github.com/zenithdb/zenith/blob/smart_checkpoint/pageserver/src/walingest.rs#L334) do this. We just receive page images from the wal.

We're either:
1. Relying on **frequent** page images that compute sends us
2. Having bad read amplification, worst case applying 256MB of wal for a single page

I'm not sure which one is the case (we can measure), but both are bad. To have good read amplification we want a close to 50/50 split between total page image size and total wal size in memory and in our delta layers. If compute is actually sending us page images with this frequency (because of full_page_writes or other mechanisms that I don't know about), then we can improve network throughput by 2x if we disable those mechanisms.

The problem becomes even more relevant when we add the upper layers of the LSM tree, since upper layers are all delta layers. So the worst case is much worse than just 256MB, and much easier to trigger.

Note that this can be implemented without adding additional write overhead at the pageserver. We can add a mechanism that replaces image layers by making sure that every window of 10 consecutive deltas has a page image for every page. This enables us to not store any image layers while still doing garbage collection correctly. 

## Tasks
- [x] run tests to measure potential impact (or get opinion by someone who already knows @hlinnaka @knizhnik ?)
- [ ] implement if it makes sense

**Comment by hlinnaka** [comment]
@antons-antons mentioned that hash indexes create an extreme case of this, as every operation (?) updates the metapage.

**Comment by knizhnik** [comment]
Current implementation does the following:
1. If WAL records contains FPI (full page image), then it is stored as image in pageserver (no wal redo is needed for this page).
2. Checkpointer process periodically reconstruct most recent pages. It is controlled by checkpoint distance (default 256 Mb) and checkpoint interval (default 1 second). For small databases checkpoint can be performed fast enough (few seconds), so potentially we can create page version fast enough, so that get_page_at_lsn will never need to reconstruct page itself.
3. When page is requested by get_page_at_lsn it is stored in local page cache. So if the same page is requested once again, there is a chance that it is still present in cache (although I think this probability is small enough).

The basic assumption is that compute node never request recently updated pages (because them are present i compute node cache).
Also there are two other (doubtful and partly contradictory) assumptions:
1. It is not possible to reach performance comparable with vanilla without holding working set at compute node
2. Total size of all tenant databases is much larger than available RAM at compute nodes.

Write amplification prevents us from doing checkpoints too frequently. But if checkpointer (or page reconstructor) will save reconstructed pages in page cache (which should be larger and may be also disk based)  and do not create image layers for them, then checkpointing can be done more  frequently.

**Comment by bojanserafimov** [comment]
> For small databases checkpoint can be performed fast enough (few seconds), so potentially we can create page version fast enough, so that get_page_at_lsn will never need to reconstruct page itself.

This is only true for GetPage@latest requests. Otherwise we still need to replay 256MB WAL to access a page. Once we add a read replica the problem will be noticeable. So I guess it's too early to start solving this issue, but it's the right time to discuss the solution.

> then checkpointing can be done more frequently

Currently frequent checkpointing creates too many small files. After LSM transition frequent checkpointing will add write amplification because it creates the need for compaction. Example: Checkpointing four 250MB files instead of one 1GB file means that those files need to be compacted later. That's write amplification.

**Comment by bojanserafimov** [comment]
I ran some tests that confirmed that whatever (if any) page images we're getting from compute, they're not enough. Will share results here https://github.com/zenithdb/zenith/issues/1380

We either need page images, or an alternative solution with the same effect (really fine image layers of some sort)

**Comment by bojanserafimov** [comment]
https://github.com/zenithdb/rfcs/pull/18/files proves that page images at the end of the delta layer are more useful than historical page images inside the layer. Also it might be wise to store these page images in an ephemeral format separate from the layered repo.

The problem still exists, but the solution I'm alluding to here is not the right one. Closing this in favor of the broader problem here https://github.com/zenithdb/zenith/issues/1481.
