### ISSUE TITLE
ERROR: could not extend file. Cluster size limit of 10000 bytes is reached (SQLSTATE 53100)

### ISSUE THREAD

**Issue by nikitashamgunov** [zenithdb/zenith#1233]
drop table if exists nikita;

create table nikita(id int, a text);

insert into nikita values(1, repeat('a', 4000));

insert into nikita values(1, repeat('a', 40000));

select * from nikita;

create or replace procedure inf()
LANGUAGE plpgsql
AS $$
begin
  for counter in 1..10000000 loop
--    while 1=1 loop
    insert into nikita select * from nikita;
  end loop;
end;
$$;

call inf();

**Comment by hlinnaka** [comment]
We set the default limit to 10 kB? :facepalm: There was a mixup with the unit, the console thought that the unit of the GUC is MB, but it's actually bytes.

We need to change the unit in the server to be megabytes. It is stored in a 32-bit integer, so if the unit is bytes, the max limit is only 2 GB. Then the default of 10000 is correct. @lubennikovaav.

 But just to be more clear, let's also set the setting as "10GB" in the console, instead of "10000". @Daniel-ef
