### ISSUE TITLE
Use page cache for image and delta layers

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#1356]
Image and delta layers don't use the page cache, every read operation results in a read() system call. That makes compaction pretty slow as it reads all the existing versions from a delta layer and writes it back out. That is currently slow and shows up in 'perf' profile. (The code in 'main' is missing that too, but it's not as obviously bad there because we don't do anything like the "compaction" there)

Also, they both have an 'index' HashMap that is fully loaded into memory on first access. Should refactor that into a page-oriented data structure and use the page cache for that too.

**Comment by knizhnik** [comment]
I do not think that we really need cache here, because delta and image layers are not expected to be accessed frequently. So probability of cache hit will be close to zero.

What we need here is buffered IO. Right now delta_layer is using BufWriter for ChapterWriter. I wonder if we also should use BufReader for Book:
```
        let book = Book::new(BufReader::new(file))?;
        let chapter = book.chapter_reader(VALUES_CHAPTER)?;
```
Right now it is not possible because of unsatisfied trait bounds:
`Book<std::io::BufReader<std::fs::File>>` 
But you have said that we can change Eric's bookfile. Can we just change 
`impl Book<File>` to `impl<R> Book<R> where R: Read,Seek` 
and use BufReader ? Does it solve the problem with performance?

It seems to be necessry only for DeltaLayer, not for ImageLayers, because 8k pages is better to read without extra copies.

**Comment by knizhnik** [comment]
Looking more at chapter_reader I realized that it can't be used with any buffered reader because it returns constant reference and any buffered reader by definition has to store some state.

So I have implemented different approach: see https://github.com/zenithdb/zenith/pull/1369

**Comment by hlinnaka** [comment]
> I do not think that we really need cache here, because delta and image layers are not expected to be accessed frequently. So probability of cache hit will be close to zero.

Why do you think they would not be accessed frequently? Only the last 1 GB of updated pages sit in the in-memory layer, *all* other accesses are to image and delta layers. Did you perhaps mean that the accesses would be very random, so that the page cache won't help much? That may be true. But even then, I doubt it would be completely random. And the index pages with the offsets to within the file are surely more frequently accessed than any actual data page, so those should be cached. Currently they are cached by slurping he index completely into memory, but that's very inflexible, and we don't have any good scheme for releasing memory. So at least that should be accessed through the page cache.

Another idea would be to mmmap() the files and let the OS handle the caching. That could be very fast. However, I'm a bit scared of mmapping. A single read error would crash the whole process. And we might run into limitations with the number of mmaps etc.

**Comment by knizhnik** [comment]
> Why do you think they would not be accessed frequently? 

It is just based on the assumption that size of shared-buffers in compute node is (should?) comparable with page cache size. It means that if working set fits in compute memory, then this page will not be requested from page server at all. And if it doesn't fit in compute memory and we have random access pattern, then probability of page cache hit is very small. If page was evicted from shared buffers at compute node, then most likely it was also evicted from page cache in pageserver which is shared by multiple tenants.
