### ISSUE TITLE
Observability

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#16]
Each event in safekeeper/pageserver should define some counters/aggregates, that would be at first stored and recalculated locally, then pushed somewhere in the general direction of metrics store like cloud watch or prometheus. Also we may adopt all the opentracing stuff -- define 'span' for each continuous event and send them to jaeger.

If we adopt this earlier that would greatly simplify benchmarking: instead of ad-hoc setup
for each test we can just run load and look into grafana/jaeger to understand what is happening.

---

Subtasks

- [x] #374
- [ ] #373 
- [x] #371 
- [x] #372

**Comment by kelvich** [comment]
Right now we want to implement following:
* instrument our rust code with https://github.com/tokio-rs/tracing and enable tracing_opentelemetry
* use telegraf for os and postgres metrics
* tracing_opentelemetry would send data in opentelemetry-collector which would forward that to grafana with {loki, cortex, tempo}

**Comment by mklgallegos** [comment]
Hi @funbringer  when you have a chance can you provide an update on this? I know we've changed course on using opentelemetry due to some issues and now we're focusing on grafana and prometheus. I'm trying to work on getting all updates directly on the the github issues (will be a lot easier to share status of an issue to entire team this way)

it would be helpful to know:

1. What is the exit criteria for this case (has it changed since switching from opentelemetry to grafana+prometheus)? By exit criteria I mean what work needs to be completed to satisfy area of observability for v0.1 milestone?
2. work left to be done (a checklist of items would be helpful) 
3. any blockers?

**Comment by mklgallegos** [comment]
related to:
#374 
#373 
#372 
#371

**Comment by kelvich** [comment]
closing, further work in separate issues
