### ISSUE TITLE
Fix current safekeeper test and port them to python

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#182]

**Comment by knizhnik** [comment]
As far as I know several people are working now on problems with wal_acceptor tests crashes/hangs. This is because I wan to share what I have investigated today:

1. Sometimes postgres instance is not stopped. I didn't understand why. My hypothesis is that pg_ctl stop -m immediate is not waiting for instance stop and then we remove postgres data dir. When I comment removing datadir I can not reproduce that problem any more. In any case removing datadir before successful completion of the tests is not good idea.

2. The problem with receiver thread. Right now there is separate thread in wal sender receiving responses from replica (replication.rs:127) The problem is that if wal_sender itself is died, this thread is still alive and reading socket.  ReplicationConn::run thread is finished because connection wit wal_proposer is not yet established. I tried to wait instead hang-out:
```
loop {
			wal_seg_size = self.timeline.get().get_info().server.wal_seg_size as usize;
			if wal_seg_size == 0 {
				error!("Can not start replication before connecting to wal_proposer");
				sleep(Duration::from_secs(1));
			} else {
				break;
			}
        }
```

3. Current wal_acceptor test configuration is close to real: computation node is streaming WAL to walkeeper and it - to page_server. The problems arise when we begin to stop/start walkeepers in our tests. Once walkeeper is offline, page_server is not able to receive the lastest WAL and so get_page_at_lsn request may hang. To fix it either walkeepr should be restarted, either page_server should try to connect to different walkeeper. The first is not possible (at least for test_wal_acceptors_restart test becuase walkeeper is stoped and started in the main thread, which is blocked in INSERT because get_page_at_lsn is blocked in page_server. SO looks like we should start/stop walkeepers in separate thread as it is done in test_race_conditions by simulate failures.
Either do no connect page server to wal_keepers and let it receive WAL from compute node.
