### ISSUE TITLE
Backup and restore page server from S3

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#230]

**Comment by kelvich** [comment]
Let's start with non-incremental postgres data directory format.

Backup can be implemented as a different kind of remote in `zenith push` utility.

Restore can be implemented as an option to `pageserever init` restoring the repo from S3. When we will have multirepo support in pageserver we can switch that to `zenith pull` which would pull new repo to running pageserver.

**Comment by ericseppanen** [comment]
If we do something like the "snapshot-first storage" RFC, then this might look quite different: there is no need for a backup of a pageserver! The pageserver would always be syncing s3 with its latest contents.

**Comment by lubennikovaav** [comment]
I agree that I don't see why we need a backup to s3 in a new design.
One more concern is that we are not 100% compatible with postgres page format.

@ericseppanen, I think we'd better join our efforts, since this feature needs exactly same remote object storage api as 'snapshot-first storage'.
Please, check my RFC that adds on  yours https://github.com/zenithdb/rfcs/pull/8#issuecomment-869529223

**Comment by mklgallegos** [comment]
Hi @lubennikovaav when you have a chance can you provide an update on this? (I'm pinging you since issue is assigned to you)

I'm working on gathering context on open issues in the v0.1 milestone. I think there have been some moving pieces with storage and this issue hasn't been updated in awhile so I wanted to check in. 

it would be helpful to know:
1. general status update
2. in the current plan will backups be needed or does the design involving automatically syncing pageserver to s3 take care of backups?
3. any blockers?

**Comment by hlinnaka** [comment]
I'm closing this issue, in favor of https://github.com/zenithdb/zenith/issues/340. An "import/export" feature makes sense too, and maybe even to/from S3, but it's a different feature.
