### ISSUE TITLE
Bulk insert failed with various symptoms

### ISSUE THREAD

**Issue by knizhnik** [zenithdb/zenith#301]
```
create table t(c1 bigint, c2 bigint, c3 bigint, c4 bigint, c5 bigint);
create index on t(c1);
create index on t(c2);
create index on t(c3);
create index on t(c4);
create index on t(c5);
insert into t values (generate_series(1,1000000),random()*1000000,random()*1000000,random()*1000000,random()*1000000);
```
hangs in _bt_moveright. It is at main branch at EC2.

It is also reproduced locally at nonrel_wal branch with the following error:
``` 
Another run cause ERROR:  index "t_c4_idx" contains unexpected zero page at block 3184
Please REINDEX it.
```

Lightweight version of this query with better locality is passed locally, but at EC2 cause the following error:

```
insert into t values (generate_series(1,1000000),generate_series(1,1000000),generate_series(1,1000000),generate_series(1,1000000),generate_series(1,1000000));
ERROR:  right sibling's left-link doesn't match: block 2550 links to 2549 instead of expected 1465 in index "t_c2_idx"
```

**Comment by knizhnik** [comment]
Some updates on this issue.It is more or less deterministically reproduced locally with the following test:
```
from contextlib import closing
import psycopg2.extras

pytest_plugins = ("fixtures.zenith_fixtures")

#
# Test insertion of larg number of records
#
# This test is pretty tightly coupled with the current implementation of page version storage
# and garbage collection in object_repository.rs.
#
def test_bulk_insert(zenith_cli, pageserver, postgres, pg_bin):
    zenith_cli.run(["branch", "test_bulk_insert", "empty"])
    pg = postgres.create_start('test_bulk_insert')

    with closing(pg.connect()) as conn:
        with conn.cursor() as cur:
          cur.execute("create table t(c1 bigint, c2 bigint, c3 bigint, c4 bigint, c5 bigint)")
          cur.execute("create index on t(c1)")
          cur.execute("create index on t(c2)")
          cur.execute("create index on t(c3)")
          cur.execute("create index on t(c4)")
          cur.execute("create index on t(c5)")
          cur.execute("insert into t values (generate_series(1,1000000),generate_series(1,1000000),generate_series(1,1000000),generate_series(1,1000000),generate_series(1,1000000))")
          cur.execute("insert into t values (generate_series(1,1000000),random()*1000000,random()*1000000,random()*1000000,random()*1000000)")
```
But errors may be different.
Most frequent case:
1. Compute node complains that index contains zero page. I inserted check in pageserver which detects whe zero page is returned. It shows that get_page_at_lsn(LSN1) using self.object_versions() retrieves zero page with LSN2<LSN1. But if we immediately repeat self.object_versions with the same key, then get object with lsn=LSN1. Why it was not located at first call? Looks like some race condition here. Previous call of wait_lsn(LSN1) should enforce that that any WAL record with lsn<=LSN1 should be stored in object storage and so be located by self.object_versions(). I found one suspicious place in walreceiver_main: it advances last_valid_lsn to `endlsn`, while LSN of  last stored WAL is `last_rec_lsn`. It can be smaller than `endlsn`, if last WAL record in the received segment is incomplete (continues at next segment). Can it cause a problem? I do not understand how. 
2. Sometimes compute nodes reports that index contais zero page but check for returned zero page at pageserver is not fired! In other words it means that compute node gets zero page but page server didn't sent it. How it is possible? Race condition in SMGR at compute node?
3. Once I get assertion failure in wal-redo postges: Assert(P_INCOMPLETE_SPLIT(pageop)); How it can happen? We either forgot to apply some WAL record which should set this bit. Either some multiblock nbtree record is not properly applied. Also I do not completely understand comment to btree_xlog_insert:
```
	/*
	 * Insertion to an internal page finishes an incomplete split at the child
	 * level.  Clear the incomplete-split flag in the child.  Note: during
	 * normal operation, the child and parent pages are locked at the same
	 * time (the locks are coupled), so that clearing the flag and inserting
	 * the downlink appear atomic to other backends.  We don't bother with
	 * that during replay, because readers don't care about the
	 * incomplete-split flag and there cannot be updates happening.
	 */
```
What does it mean "eaders don't care about the incomplete-split flag "? Does this assertion failure refutes this statement?

**Comment by petergeoghegan** [comment]
@knizhnik In Postgres nbtree, page splits are done in two separate atomic operations -- 1. the initial page split, and 2. the insertion of the new downlink/pivot tuple into the parent (this points to the new right sibling page created in step 1). This assertion is intended to catch the case where step 1 was apparently missed, which should never happen.

The "readers don't care about the incomplete-split flag" needs to be put in context. In general step 2 happens immediately after step 1, in the same backend that caused the page to split. But in rare cases where there is a hard crash "in between" the two steps, the next writer that reaches the incompletely split page will then have to perform step 2 itself. It's important that only one writer attempt this at the same time, since it would be wrong for two concurrent writers to decide to complete the split for the same page (that would corrupt the index). The first writer that locks the page with the flag set must not release the lock until it locks the parent and then inserts the new downlink, before finally clearing the flag (aka step 2). So whoever locks the incomplete-split page initially also does everything, and must not allow any other writer to see the flag and try to do the work that it has decided to do (i.e. step 2, completing the split).

The comment is just saying that we don't need to be so careful about things during recovery, because you can only have one "writer" (the startup process) in any case -- there is no danger in letting backends observe the incomplete split flag because they can't be writers during recovery. Of course this might not be true for us, with Zenith.

**Comment by petergeoghegan** [comment]
You might want to use amcheck's bt_index_check() function to test this. It only needs an AccessShareLock, but nevertheless verifies quite a lot about the tree structure -- it notices when things look inconsistent *across* pages. Especially in Postgres 14.

The specific error "ERROR:  right sibling's left-link doesn't match: block 2550 links to 2549 instead of expected 1465 in index "t_c2_idx"" sounds like a case of the first atomic operation (step 1) not actually working as an atomic operation *across* same-level pages (these are almost certainly leaf level pages, though in theory they might be internal pages). In other words, it looks like the problems start even before we reach step 2 (we might also have problems in step 2, but we should focus on step 1 first). The fundamental issue is that we need to see consistent versions of multiple pages in the B-Tree. For example step 1 needs to make changes to 3 pages appear as one atomic operation. These pages are the original/split page, its original right sibling page (which needs to have its leftlink updated), and the new right sibling page (which is a whole new page).

See the function bt_recheck_sibling_links() (added in the past year by Postgres commit 39132b784ae) to get a detailed idea of what we expect for the first step, and why that is. That's a good starting point for fixing the more general issue of needing multiple pages to appear consistent following a single atomic step/WAL record. I committed that code, but the patch is from Andrey Borodin. The way I tested that patch might help here -- I suppose that you could use strategically placed pg_usleep() calls in about the same way to debug this issue.

**Comment by petergeoghegan** [comment]
> @knizhnik In Postgres nbtree, page splits are done in two separate atomic operations -- 1. the initial page split, and 2. the insertion of the new downlink/pivot tuple into the parent (this points to the new right sibling page created in step 1). This assertion is intended to catch the case where step 1 was apparently missed, which should never happen.

Correction: This assertion is intended to catch the case where step 2 has *already completed* (say by replay of the same WAL record), which should never happen -- the REDO routine expects that the flag will be set when it goes to clear the flag. I suppose that it might also catch the case where somehow there never was a step 1, and therefore the page-level incomplete split flag was somehow never set in the first place. This second scenario seems kind of absurd to me, but I don't yet know enough about Zenith to be able to rule it out completely.

**Comment by petergeoghegan** [comment]
BTW the Socrates paper has something to say about the problems with B-Trees -- see "4.5 Secondary Compute Node". B-Trees tend to rely on cross-page consistency at the data structure level in specific subtle ways. It's possible that we'll need a fix that tweaks something about the locking protocol itself, even though we can probably avoid that kind of thing in most other places.

**Comment by knizhnik** [comment]
Thank you for reply.
Looks like the problem was caused by GC: if I switch it off, then (after fixing memory leak in wal-redo postgres),
test is completed in ... 5029.13s (1:23:49)
The same test with local postgres and similar configuration (1Mb shared buffers, fsync=off) is completed in 1m22,352s.
Well, there is non-release rust version and we have not concerned much about optimizations ... but ~100times difference is really upset.

**Comment by knizhnik** [comment]
[pageserver.svg.gz](https://github.com/zenithdb/zenith/files/6791085/pageserver.svg.gz)
Profile of page server

**Comment by knizhnik** [comment]
Results of release version: 1817.91s (0:30:17)

**Comment by knizhnik** [comment]
Profile of release versions. Looks like most of the time is spent in compress/decompress.
[pageserver.svg.gz](https://github.com/zenithdb/zenith/files/6791824/pageserver.svg.gz)

**Comment by knizhnik** [comment]
Looks like I found the reasons of the problem.
The problem is caused by updating relation metadata when page is materialized by get_page_at_lsn.
When get_page_at_lsn is called by GC at some horizon, then we update elation metadata according to this horizon. And in conjunction with relation metadata cache it doesn't work correctly.

**Comment by knizhnik** [comment]
I have implemented in-memory storage (branch inmem_store).
Time of this test is reduced to 642.37s (0:10:42) which is ~three time faster than RocksDB but still ~10 time slower than local postgres.

**Comment by knizhnik** [comment]
Time with new Heikki's storage: 645.40s (0:10:45)
Profile: 
[layered-store.svg.gz](https://github.com/zenithdb/zenith/files/6808687/layered-store.svg.gz)

**Comment by mklgallegos** [comment]
Hi @knizhnik  - this item was put into the done category during the milestone v0.2 planning session on 2021-07-30 by @kelvich. I'm closing out. Please re-open if I am mistaken.
