### ISSUE TITLE
Multitenancy for pageserver

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#304]
Add command create_tenant (create_repo?) which would basically add do actions like 'paserver init' in subdirectory of workdir.

**Comment by LizardWizzard** [comment]
Extended description.
Basically create indirection layer for tenants data storage in page server. 

Goals:
- [ ] Page server init process adds tenant named "default", and initializes directories in "<page_server_data_dir>/tenants/default". 
- [ ] New command `create_tenant` initializes new tenant in `<page_server_data_dir>/tenant`. Other commands are modified to take `tenant_id` as a parameter when needed.
- [ ] Page cache global Repository becomes `HashMap<tenant_name, Repository>`. It is populated during `page_cache::init()`
- [ ] For connections coming to page server `tenant_name` is required to identify which storage to use. Tenant name is passed as a parameter in query like `timeline_id`. 
- [ ] Tenant name is passed to postgres through config variable and used in requests to pageserver.

**Comment by ericseppanen** [comment]
I would expect that a tenant would be integrated with the cloud management of user accounts, permissions, etc.

Perhaps instead of having the pageserver know about tenant names, it should manage access by requiring an auth token; the cloud control plane could generate signed tokens (which contain the database/timeline id).

I don't think a default tenant makes much sense in the cloud deployment; I would imagine that a new pageserver should start up and do nothing but wait for commands; then the control plane would send it a command to start a particular database on behalf of a particular user.

**Comment by LizardWizzard** [comment]
In my current understanding pageserver needs to know only names of tenants whose databases are located on that particular pageserver, because it is interacting with compute postgres also launched on behalf of a particular tenant. So pageserver should be able to accept connections and perform some kind of routing to needed data directory, wal redo instance etc.

Probably, complete story consists of the following steps:

1. Something like "create instance" is pressed by user in the ui
2. Control plane finds page server and issues to it "create tenant"
3. Control plane starts up compute postgres with the address of that page server in the config
4. Compute postgres connects to page server and becomes ready to process user requests

I agree that default tenant does not make much sense for cloud deployment, it's suitable for local setup/tests. So I can add an option to page server init, something like "with default tenant".

Also, can there be a case when a user shuts down an instance, so pageserver evicts data to e.g s3 so when the instance is started again pageserver should download that data on create tenant?

To preserve changes in incremental fashion, I think that case can be handled in separate issue. Also I think for this task commands can be issued from cli and this can be integrated with ui separately. 

So, lets discuss usage of auth tokens in more detail. For clarification, is this a supposed sequence of actions?

1. Cloud management ui issues a token when a user starts up a new instance
2. This token is passed to compute postgres via config variable
3. When compute postgres connects to pageserver it passes token in arguments so pageserver verifies this token (locally or using cloud console?)

**Comment by kelvich** [comment]
Console is already integrated with the pageserver. When user creates cluster console connects to pageserver and asks it to create a branch of main branch (which is kept empty). That is crutch and we need to decouple users into different tenants inside pageserver. As well as pass initdb options for a new tenant/repo.

> Perhaps instead of having the pageserver know about tenant names, it should manage access by requiring an auth token

And token need to contain some info to identify which tenant inside the pageserver we are referring to. We can call that piece  of info id or name but ultimately it is just an argument to create_tenant command.

Let's focus in this task on multi-tenancy itself not on auth. Certainly all pageserver API should be covered with auth (relevant issue https://github.com/zenithdb/console/issues/86).

**Comment by mklgallegos** [comment]
hi @LizardWizzard when you have a chance can you provide an update on this issue? (I'm browsing through issues in the v0.1 milestone and just wanted to get an update on current status for issues tracking in this milestone) thank you

I would like to know:
1. general status update
2. any blockers?

**Comment by LizardWizzard** [comment]
Hi @mklgallegos, this is awaiting on review. I've just rebased it with new changes from main. See related PR's: https://github.com/zenithdb/zenith/pull/318 https://github.com/zenithdb/postgres/pull/59

**Comment by mklgallegos** [comment]
Hi @kelvich / @LizardWizzard 

Are you planning to expose the concept of a tenant to end users? 

If the concept of a tenant is planned to be exposed to end users can you describe how as an end user I would need to interact with the concept of a tenant? Examples would be helpful for me.

I'm trying to keep the end user facing UI for zenith (web console, cli, api) as minimal as possible.

Thank you, mike

**Comment by mklgallegos** [comment]
> That meant to be an internal API for web console to keep each cluster in its own tenant

all good, thanks for confirming

**Comment by LizardWizzard** [comment]
resolved by #318
