### ISSUE TITLE
implement size quotas for the of the database/timeline in storage

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#316]
a) track timeline size

b) report quota overflow to postgres (as an error on extend?)

**Comment by lubennikovaav** [comment]
The goal is to implement disk space quotas for pageserver, limiting space usage per zenith client.
From pageserver point of view a client is a tenant that stores data in multiple branches or timelines.

So the first question is if we should limit size per timeline or per tenant?

The problem is that now we don't have any feedback from pageserver to compute node.
All the data flows via WAL stream, which is processed later and zenith_extend() currently does nothig.
This way we can write a lot before pageserver has a change to answer with anythig.

One idea is to request timeline size each Nth extend and deny extend if pageserver says that the limit was reached. 
Should we wait for last lsn as in page read requests or we may allow this value to be a bit outdated?

What I implemented in a first draft in #320 is a limit of space occupied by one compute node.
When a node is started, we send initial size of a timeline, then increase it for each extend() operation and decrease when truncate() or unlink() happens.
zenith_extend() checks the size and when the limit defined by GUC is reached, it will throw an error,
It works almost like regular PostgreSQL out-of-disk-space error.

This can be a good feature on it's own, but it doen't help to limit disk usage when multiple compute nodes are present.

Two more questions that probably deserve their own issues:
How should we limit s3 space usage. And what about WAL archive size limits?

**Comment by lubennikovaav** [comment]
Meeting notes:
- Don't limit or throttle WAL streaming, since operations that aim to free space can generate a lot of WAL (i.e. vacuum, reindex).
- Consider this limit as a soft limit.
- Add warnings about approaching the limit.
- Define disk usage as pg_database_size() (sum for all databases), i.e. what PostgreSQL thinks about it's data.
Other metrics (real space usage on pageserver and in s3) will be handy for internal use.
- Show disk usage in console (not just at a moment, but rather how it changes over time).
- We can use HotStandbyFeedback or NOTICE to inform compute node about reaching the limit

**Comment by LizardWizzard** [comment]
Decided to continue with collecting timeline and possibly repo sizes and exposing them in pageserver http api, also explore possibility to make size retrieval cheap enough for checks on every write
