### ISSUE TITLE
JWT auth for pageserver

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#323]
Right now we don't have any internal check that would prevent one compute node from accessing neighboring pageserver tenants/timelines, getting a list of them, etc.
Let's do the following:

compute node --> pageserver/safekeeper:
* during compute node creation console would generate and put JWT token (scope=tenant, tenant_id=$id) inside vm, e.g. to .env file
* postgres would read this token from the environment variable (corresponding systemd unit needs to set this variable) and pass it to the safekeeper in the startup package
* safekeeper checks token using the console public key and uses it to connect to the pageserver
* all page requests would use the same JWT auth on connection.
* JWT token with scope=tenant would not allow most API access (list_tenants, list_branches, etc)
* In this scenario we can omit refresh tokens -- we control compute node and we can "revoke" access by just shutting compute node down. We may later add refresh tokens for paranoia-mode=on and deal with token refreshes inside compute node, but let that be a separate issue with lower priority.

web console --> pageserver/safekeeper:
* console self-issues JWT with scope=pageserver_api and creates/lists tenant and timeline using this token.

corresponding ticket for the console: zenithdb/console#109

**Comment by LizardWizzard** [comment]
I've tested an approach using jwt passed as a clear text password. It works for python client, rust postgres and with small tweaks also works for psql. Caveat for psql is that it silently truncates password to 100 symbols. But the limit is applied only to password prompt, so using `export PGPASSWORD=very_long.token` before call to psql allows to submit longer passwords.

Also there are some people already using this approach. I've found some discussions which mention that token in password used by people at Zalando and Amazon RDS.

Amazon RDS: https://www.postgresql.org/message-id/flat/CAOhmDze1nqG2vfegpSsTFCgaiFRsqgjO6yLsbmhroz2zGmJHog@mail.gmail.com
Zalando: https://www.postgresql.org/message-id/CAFh8B%3Dk6N5Y2nknTkmA9WmzbmSxOzb5WL8UAnvaBLK%2BFJn2w8w%40mail.gmail.com

**Comment by LizardWizzard** [comment]
We've disscussed this a little in private, here is the summary:
1. For postgres protocol JWT is passed via plaintext password authentication.
2. Pageserver uses a new option in config file to choose auth type, which can be Trust or ZenithJWT.
3. Incoming connections to pageserver are authenticated using scheme chosen in config.
4. Currently communication between postgres and safekeeper uses custom protocol, so we decided to postpone adding auth into it until the implementation is moved to libpq. After that posgtres can read token from environment variables, and add it to connection string.
5. For callmemaybe call to page server postgres uses callmemaybe_connstring config variable, so in this case token is specified in password field of the connection string during node creation.
6. Because of 4 safekeeper uses hardcoded token in communication with pageserver.
7. CLI is modified to create keys for signing tokens during init. Token for using page server api is issued locally and saved in cli config.
