### ISSUE TITLE
Async front for proxy

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#342]

**Comment by stepashka** [comment]
depeneding on implementation of #117 implementing this task may become feasible

**Comment by LizardWizzard** [comment]
@stepashka Could you please elaborate on how this relates to #117?

**Comment by stepashka** [comment]
@LizardWizzard , this was a note from my chat with @funbringer 
@funbringer mentioned that @yeputons is working on something that may help here to this issue
AFAIK #117 this is the main project @yeputons is working on, so I connected these two issue together, but could have been wrong in doing so!

**Comment by LizardWizzard** [comment]
Got it, this is correct, thanks!

**Comment by bojanserafimov** [comment]
Does async front mean tokio tasks instead of threads? If that's the case, it might require a lot of work since we rely on `Read` and `Write` traits for everything (tcp proxy for example), but they will block tokio. I think hyper (our http server) implements their own async version of Read and Write, and there's also [this](https://github.com/async-rs/async-std), but I'm not sure how good it is.

**Comment by kelvich** [comment]
> Does async front mean tokio tasks instead of threads?

Yeah, that was the plan

> If that's the case, it might require a lot of work since we rely on `Read` and `Write` traits for everything (tcp proxy for example), but they will block tokio. I think hyper (our http server) implements their own async version of Read and Write, and there's also [this](https://github.com/async-rs/async-std), but I'm not sure how good it is.

Yep, @funbringer and @arssher have a plan on how to approach this.

**Comment by bojanserafimov** [comment]
seems done https://github.com/zenithdb/zenith/pull/1270
