### ISSUE TITLE
XLOG_MULTIXACT_ZERO_OFF_PAGE handled twice in save_decoded_record

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#453]
Found by clippy:
```
error: this `if` has the same condition as a previous `if`
   --> pageserver/src/restore_local_repo.rs:469:19
    |
469 |         } else if info == pg_constants::XLOG_MULTIXACT_ZERO_OFF_PAGE {
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(clippy::ifs_same_cond)]` on by default
note: same as this
   --> pageserver/src/restore_local_repo.rs:455:12
    |
455 |         if info == pg_constants::XLOG_MULTIXACT_ZERO_OFF_PAGE {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ifs_same_cond
```
Probably second one should be `XLOG_MULTIXACT_ZERO_MEM_PAGE`. @hlinnaka Is it correct?

**Comment by hlinnaka** [comment]
> Probably second one should be XLOG_MULTIXACT_ZERO_MEM_PAGE. @hlinnaka Is it correct?

Yes.

We really need a tool described here: https://github.com/zenithdb/zenith/issues/326. Even without that, I wonder if we should have more checks somewhere? I guess it's not an error if we fail to zero the page, if we implictly zero it the first time it's actually written to. I think we do that. Perhaps we should be more strict. Or perhaps we already print warnings about that, too, but we've haven't noticed?

It would be nice to have more assertions in the code. However, we pretty much never want to panic the pageserver, because it's multi-tenant, and we don't want to bring down all the tenants if one of them is experiencing a problem. Perhaps a debug-build only assertion, or grep the logs for errors and warnings after tests and complain if there are any?

**Comment by LizardWizzard** [comment]
We may want to add a build configuration variable like "with_assertions" and use a macro which panics when binary was built with assertions and logs an error if assertions were disabled.

In general IMO safety checks are always a good thing, so during coding it is always desirable to guard against unwanted states even if they are not totally invalid. 

Also I think it's a good idea to check in tests for erroneous log output regardless of debug assertions, probably this can be even a behaviour by default, with ability to disable for tests which check that something breaks only in expected way (e. g. healing after a disconnect)
