### ISSUE TITLE
Review terminology in layered repo

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#520]
While reading the code, I noticed some confusing terminology. Let's clean it up.

1. Is there any difference between `snapshot files` and `layer files`?
2. `GC` and `checkpoint` are used interchangeably. Should we leave just one term?
3. When we speak about dropped relations, we use `unlink` and `drop`. I.e. `put_unlink` function sets `drop_lsn`. Same question as above.
4. There is a `get_end_lsn()` function, which returns quite different things for each layer. It definitely lacks comments.
5. Does `layer.is_incremental()` differs from `layer.is_delta()`? I feel like i don't understand the term `incremental` in this context.
6. It's either a bug or a wrong comment:
```
-- in layer_map.rs
      // Ignore delta layers.
      if layer.is_incremental() {

-- in inmemory_layer.rs
    fn is_incremental(&self) -> bool {
        self.img_layer.is_some()
    }
```

**Comment by hlinnaka** [comment]
> While reading the code, I noticed some confusing terminology. Let's clean it up.

+1

>     1. Is there any difference between `snapshot files` and `layer files`?

No. Let's replace "snapshot files" with "layer files", the "snapshot" term is confusing.

>     2. `GC` and `checkpoint` are used interchangeably. Should we leave just one term?

They're not the same thing. Checkpoint flushes recent in-memory layers to disk, while GC removes old on-disk layers/files that are no longer needed.

Both actions are performed by the checkpointer thread, which is a bit confusing. Maybe rename the thread?

>     3. When we speak about dropped relations, we use `unlink` and `drop`. I.e. `put_unlink` function sets `drop_lsn`. Same question as above.

No difference here. Yeah, we should clean that up and stick to one term.

>     4. There is a `get_end_lsn()` function, which returns quite different things for each layer. It definitely lacks comments.

+1

>     5. Does `layer.is_incremental()` differs from `layer.is_delta()`? I feel like i don't understand the term `incremental` in this context.

"incremental" means that the layer doesn't contain all data needed to reconstruct pages in the range; you need the predecessor layer, too. Or to put it the other way, a non-incremental layer is self-contained and doesn't depend on any other layers.

Delta layers are always incremental, while image layers are not. In-memory layers can be incremental or not. (An in-memory layer that's created for a new relation is not incremental, but the ones after that are).

In principle, a delta layer could also be marked as non-incremental, if it happens to contain a full page image of every page in the segment. We don't do that currently, but it could be a worthwhile optimization.

>     6. It's either a bug or a wrong comment:
> 
> 
> ```
> -- in layer_map.rs
>       // Ignore delta layers.
>       if layer.is_incremental() {
>
> -- in inmemory_layer.rs
>     fn is_incremental(&self) -> bool {
>         self.img_layer.is_some()
>     }
> ```

Hmm, yeah, that "Ignore delta layers" is inaccurate or misleading at least. It's true that we ignore delta layers here, because they're always incremental. And because this is in a loop over the historic layers, it won't encounter in-memory layers here. But the point here is to ignore all incremental layers. Whether they're delta layers or something else isn't important.

**Comment by lubennikovaav** [comment]
Thank you!
I'll create a PR with these changes.

**Comment by lubennikovaav** [comment]
A few more questions:

1. `If a file has been dropped, the last layer file for it is created with the _DROPPED suffix, e.g.` 
Dropped rel is always represented by delta layer, right?

2. Is there any difference between `layer.is_dropped()` and `layer.get_seg_exists(self.end_lsn)` ?

3. Do we need `ancestor` file in the timeline directory, given that we have the same info in `metadata` file?

4. `cli-v2-story.md` is outdated, right?
