### ISSUE TITLE
Explicit wait_lsn()

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#521]
Extracted from https://github.com/zenithdb/zenith/pull/496#discussion_r700610759

Some problems with the current wait_lsn() usage:

* it is deadlock-prone: we are calling timeline `get_*` functions that call `wait_lsn` from walreceiver. And walreceiver is the only thing that advances LSNs
* some callers need consistent pair of (current_lsn, prev_lsn) and calling `wait_lsn` implicitly makes it hard to return `prev_lsn`.
* there is no way in current waiting mechanism to return `prev_lsn` of awaited `current_lsn`.

I suggest to do the following:

* make all public functions in timeline non-waiting
* instead of `Lsn` accept `Option<Lsn>` where `None` means "take latest"
* assert that arg_lsn <= current_record_lsn in all timeline functions
* set lsn to None for all calls originating from WalReceiver
* assert that wait_lsn isn't called from WalReceiver
* call wait_lsn explicetly where it is needed (page_service and basebackup)
* pass both (lsn, prev_lsn) in waiting queue so that wait_lsn can return that pair

**Comment by hlinnaka** [comment]
+1 on all of this except this one:

> * instead of Lsn accept Option<Lsn> where None means "take latest"

Do you mean in the `get_page_at_lsn()` etc. functions? Taking the latest page version seems pretty sloppy in general. I don't think there are many places where that's the right thing to do, so I'd like to force you to think what the correct LSN is, rather than make it too easy to just pass None. So I think it would be better to call `get_last_record_lsn()` in the caller explicitly, and pass that back to `get_page_at_lsn()`, in the few places where that's the right thing to do.
