### ISSUE TITLE
Http endpoint in pageserver for basebackup

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#557]
Basebackup psql command has quite a few parameters without well defined schema and parsing is quite messy, so we can use http here instead. (Do not forget to update swagger schema)

**Comment by SomeoneToIgnore** [comment]
After a series of discussions, had decided against implementing it.

The main motivation for a change stays the parameter parsing and clarity, yet to move basebackup on http entirely (removing it from psql) we would need to:

* adjust [`zenith_ctl`](https://github.com/zenithdb/zenith/blob/76b74349cbed8ef2f64c19f8b991526d69287a24/compute_tools/src/bin/zenith_ctl.rs#L91): currently, it is a wrapper around psql and does not use http _client_ capabilities at all.
* adjust [cluster_spec.json](https://github.com/zenithdb/zenith/blob/8f0cd7fb9f249c2635c77343939bace9f04e7b41/compute_tools/tests/cluster_spec.json) so that zenith_ctl gets a proper connection string to pageserver, apply it cluster-wide
* deal with HTTP byte streaming without accumulating entire basebackup tarball in memory
[Currently](https://github.com/zenithdb/zenith/blob/f67d010d1bf3678eb8a287d47bac3fe1eed3e8cc/pageserver/src/page_service.rs#L535-L541) it's done with psql-specific `CopyDataSink` wrapper that would not work for http.
Also, we use synchronous API everywhere, so both archive creation and http response writing should be rewritten to async for that


All this combined already feels like a big task to do and there should be better reason to pull that of than the sake of parameter refactoring.
Also to note, current basebackup has tenant id, timeline id and lsn as parameters, which is not that dire.
