### ISSUE TITLE
Fix disk_consistent_lsn handling

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#566]
I noticed that in a `branch_timeline()` call we set ```disk_consistent_lsn: start_lsn,```
https://github.com/zenithdb/zenith/blob/main/pageserver/src/layered_repository.rs#L182

Is that correct? I don't see any guarantee that all data up to `start_lsn` was persisted on disk. 
I think it should be `disk_consistent_lsn: ancestor.disk_consistent_lsn` 

@hlinnaka, FYI

**Comment by hlinnaka** [comment]
Hmm, tricky question. It actually *is* guaranteed that there isn't data older than `start_lsn` on the new timeline. Because when you create a branch, there is no data on it. And any new data will have > `start_lsn`.

It's true though that there might be data older than that in the ancestor timeline that hasn't been flushed to disk yet, and it's part of the history of the new timeline.

I think it's correct as it is, for the current usage of `disk_consistent_lsn`. A comment to explain that would be good though.

**Comment by lubennikovaav** [comment]
Thank you for the explanation. 
So `disk_consistent_lsn` only relates to the state of one timeline and we will check it and re-process WAL for each timeline separately, right?

**Comment by hlinnaka** [comment]
That's right

**Comment by kelvich** [comment]
@lubennikovaav what's the status here?

**Comment by stepashka** [comment]
during a chat with @lubennikovaav  we realised this was more of a question, so we can close this
