### ISSUE TITLE
page cache atomic variable accesses use wrong ordering

### ISSUE THREAD

**Issue by ericseppanen** [zenithdb/zenith#57]
`page_cache.rs` has quite a few places where we see code like this:

```
self.last_valid_lsn.store(lsn, Ordering::Relaxed);
// ...
self.last_valid_lsn.load(Ordering::Relaxed),
```

This is not a valid use of `Ordering::Relaxed`. We may get away with it for a while, but the semantics of `Relaxed` would allow the compiler/CPU to do things we clearly don't intend.

The `load` and `store` accesses should be `Acquire` and `Release`, respectively. I don't recall what the right ordering should be for things like `fetch_add`...

**Comment by ericseppanen** [comment]
If anyone's interested in a good resource on atomics and memory ordering in Rust, I recommend Jon Gjengset's recent video on this topic: https://youtu.be/rMGWeSjctlY

**Comment by ericseppanen** [comment]
It would also be nice to clean up some of the values that are duplicated inside and outside the lock: `first_valid_lsn`, `last_valid_lsn`, `last_record_lsn`.

I think we could just drop the versions inside the lock?

@hlinnaka, any objection to combining these? Are there any dependencies between them? Any expectations that multiple values will be modified as a group (atomically)?

**Comment by hlinnaka** [comment]
> This is not a valid use of Ordering::Relaxed. We may get away with it for a while, but the semantics of Relaxed would allow the compiler/CPU to do things we clearly don't intend.

The LSN fields outside the lock are only used for stats collection in get_stats(). We don't care much about the accuracy of those, so Ordering::Relaxed should be fine. It would be nice to get an atomic snapshot of all the values together, because it would look weird if e.g. `first_valid_lsn' was greater than `last_valid_lsn`, but as long as it's only used for stats that's acceptable too. More comments would be in order though.

> I think we could just drop the versions inside the lock?

Yeah. And `seqwait_lsn` is yet another copy of `last_valid_lsn`. If we remove the versions inside the lock, then we need to use more strict orderings when accessing them. 

Another approach would be to remove the copies outside the lock, and bite the bullet and acquire the Mutex in get_stats(). It's not called very frequently, and doesn't hold the mutex for long. And it's a bit premature to try optimizing this anyway, so whatever is simplest and most readable at this point.

PS. I just noticed that `add_assign` is bogus: it doesn't make sense to add two LSN values together.

**Comment by kelvich** [comment]
this could be closed, right?
