### ISSUE TITLE
psql: error: FATAL:  role "zenith_admin" does not exist

### ISSUE THREAD

**Issue by spullara** [zenithdb/zenith#601]
When running through the README, I get this error when running:

`psql -p55432 -h 127.0.0.1 -U zenith_admin postgres`

Removing the `-U zenith_admin` allows me to connect and continue.

**Comment by hlinnaka** [comment]
Strange, it does require `-U zenith_admin` for me:
```
~/git-sandbox/zenith$ ./target/debug/zenith init
initializing tenantid 51b847b56a4759e7a7af6d974ec7fabd
created initial timeline dbbcf580f3bb69e1ae01c0520263dd5d timeline.lsn 0/169C3C8
created main branch
pageserver init succeeded
~/git-sandbox/zenith$ ./target/debug/zenith start
Starting pageserver at 'localhost:64000' in '.zenith'
Pageserver started
~/git-sandbox/zenith$ ./target/debug/zenith pg start main
Starting new postgres on timeline main...
Extracting base backup to create postgres instance: path=.zenith/pgdatadirs/tenants/51b847b56a4759e7a7af6d974ec7fabd/main port=55432
Starting postgres node at 'host=127.0.0.1 port=55432 user=zenith_admin dbname=postgres'
waiting for server to start.... done
server started
~/git-sandbox/zenith$ ./tmp_install/bin/psql -p55432 -h 127.0.0.1 postgres
psql: error: connection to server at "127.0.0.1", port 55432 failed: FATAL:  role "heikki" does not exist
~/git-sandbox/zenith$ ./tmp_install/bin/psql -p55432 -h 127.0.0.1 -U zenith_admin postgres
psql (14beta1)
Type "help" for help.

postgres=# 
```

**Comment by kelvich** [comment]
Did you tried playing with zenith more than two month ago, more specifically before c4b2bf7? If that is the case you probably have an old postgres data directory in .zenith where that user wasn't created during init. Otherwise I don't see a way how system user may leaked into `initdb` run.

Try deleting it before `zenith init`:
```
./target/debug/zenith stop  # if pageserver is running
rm -rf .zenith
```

Or that may be some problem with Makefile where it would not call `cargo build` and you end up with old binary. In that case manual `cargo build` should help.

**Comment by spullara** [comment]
I tried that before filing the ticket. Must be some old data somewhere else. All my binaries are up to date.

**Comment by spullara** [comment]
Ok, the binaries were up to date but the source was very old. I didn't realize that I had already checked it out and needed a pull rather than clone.
