### ISSUE TITLE
Possible replication failure on staging

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#935]
There is a problem with one of the clusters (325). @kelvich suggested that replication between safekeeper and pageserver might've stuck.

Observable behavior is a timeout during call to basebackup. There is a problem in pageserver error handling so basebackup error appears in pageserver logs like that:
```
2021-11-23T13:10:08.884741Z ERROR page server thread exited with error err=Timed out while waiting for WAL record at LSN 1/29D15638 to arrive, disk consistent LSN=1/29D07CD0 
```
And client (compute tools) sees this as a broken connection during archive downloading:
```
compute-node-325	Caused by:
--
  |   | compute-node-325
  |   | compute-node-325	Error: failed to iterate over archive
```

compute logs prior to the error:
```
compute-node-325	2021-11-23 16:15:20.779 UTC [compute-monitor] INFO: cannot connect to postgres: error connecting to server: Cannot assign requested address (os error 99), retrying
--
  |   | compute-node-325	2021-11-23 16:15:19.818 UTC [main] INFO: safekeepers synced at LSN 1/29D15638
  |   | compute-node-325	2021-11-23 16:15:19.779 UTC [compute-monitor] INFO: watching Postgres activity at postgresql://zenith_admin@localhost/postgres
  |   | compute-node-325	2021-11-23 16:15:19.776 UTC [main] INFO: starting safekeepers syncing
  |   | compute-node-325	2021-11-23 16:15:19.776 UTC [http-endpoint] INFO: starting HTTP server on 0.0.0.0:3080
```

@petuhovskiy could you please take a look?

**Comment by petuhovskiy** [comment]
I looked at the replication thread for this tenant in pageserver and found out that it's stuck in `postgres::client::Client` destructor, which is called at the end of [walreceiver_main](https://github.com/zenithdb/zenith/blob/0650e51f0b8b27a4b2c5818bb13912111b92a99d/pageserver/src/walreceiver.rs#L178). Stacktraces of the stuck thread:
- [short](https://gist.github.com/petuhovskiy/82d70354dcba7d634a61dfe8fe4bc37c)
- [full](https://gist.github.com/petuhovskiy/bd672d8bfc60647948efb998ef0f46fd)

It looks like the issue https://github.com/sfackler/rust-postgres/issues/755 in rust-postgres.

**Comment by kelvich** [comment]
Good catch! So it seems rust-postgres tries to properly close the connection and await for `Poll::Ready(None)`. I assume that underlying tcp connection is alive? is there counterpart thread in safekeeper?

**Comment by petuhovskiy** [comment]
Yeah, tcp connection and safekeeper thread are alive and sk sends KeepAlive message every second, but receives no response.

**Comment by petuhovskiy** [comment]
I tried to reproduce this "stuck" error with client code similar to one in pageserver, and also tried to use postgres as a replication server. What I got:
- `postgres::client::Client` works "ok" with postgres, i.e. doesn't hang in drop()
- `postgres::client::Client` hangs in drop() when used with safekeeper

What happens in `postgres::client::Client` on drop():
- [close_inner() call](https://github.com/sfackler/rust-postgres/blob/844a27a074c9905832752b736073a4a68d616c7a/postgres/src/client.rs#L568)
- CopyBothReceiver [sends CopyFail to server](https://github.com/sfackler/rust-postgres/blob/fc10985f9fdf0903893109bc951fb5891539bf97/tokio-postgres/src/copy_in.rs#L57)
- [poll_block_on waits](https://github.com/sfackler/rust-postgres/blob/844a27a074c9905832752b736073a4a68d616c7a/postgres/src/client.rs#L571) until underlying tcp socket is closed

Safekeeper doesn't handle CopyFail message and doesn't close tcp socket. That's why client hangs indefinitely. 

Postgres also doesn't handle CopyFail message but have [assert for unknown message types](https://github.com/zenithdb/postgres/blob/08878b19d3cae5a1bd765bf7396187b6b806c6ac/src/backend/replication/walsender.c#L1756). On CopyFail, assert fails and tcp socket closes.

**Comment by kelvich** [comment]
>  assert for unknown message types. On CopyFail, assert fails and tcp socket closes.

So seems that postgres does not expect any CopyFail during the replication (related https://github.com/zenithdb/zenith/issues/458). Look like that is a problem/issue in rust-postgres replication client (it probably should add some flag to skip that message during copy).

> Safekeeper doesn't handle CopyFail message

I think it does: https://github.com/zenithdb/zenith/blob/main/walkeeper/src/replication.rs#L124 and closes thread
